# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpinstaller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='mpinstaller.MetadataCondition'),
        ),
    ]
